#define SUCCESS 1

#define ERR_SEEK -1
#define ERR_READ -2
#define ERR_WRITE -3
#define BLOCKSIZE_FAILURE -4
#define INIT_FILE_FAILURE -5

#define MKFS_FAILURE -6
#define ERR_FILE_NAME_LENGTH -7
#define ERR_TFS_MOUNT -8
#define ERR_INVALID_TFS -9
#define ERR_TFS_UNMOUNT -10
#define ERR_TFS_NOT_MOUNTED -11